import type { Product, Customer, Sale } from "./types";

const img = (id: string) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=800`;

export const CATEGORIES = [
  "Electronics",
  "Apparel",
  "Home Goods",
  "Office",
  "Grocery",
  "Hardware",
];

export const PRODUCTS: Product[] = [
  {
    id: "p-001",
    name: "Aurora Wireless Earbuds",
    sku: "AUR-EAR-001",
    category: "Electronics",
    purchasePrice: 38,
    sellingPrice: 79,
    stock: 24,
    image: img("3394650"),
  },
  {
    id: "p-002",
    name: "Meridian Desk Lamp",
    sku: "MER-LMP-002",
    category: "Home Goods",
    purchasePrice: 22,
    sellingPrice: 49,
    stock: 3,
    image: img("1112598"),
  },
  {
    id: "p-003",
    name: "Field Canvas Tote",
    sku: "FLD-TOT-003",
    category: "Apparel",
    purchasePrice: 11,
    sellingPrice: 34,
    stock: 52,
    image: img("2905238"),
  },
  {
    id: "p-004",
    name: "Quartz Mechanical Pencil",
    sku: "QTZ-PL-004",
    category: "Office",
    purchasePrice: 3,
    sellingPrice: 9,
    stock: 0,
    image: img("625329"),
  },
  {
    id: "p-005",
    name: "Atlas Insulated Bottle",
    sku: "ATL-BTL-005",
    category: "Home Goods",
    purchasePrice: 8,
    sellingPrice: 24,
    stock: 18,
    image: img("1188649"),
  },
  {
    id: "p-006",
    name: "Heliograph Smart Plug",
    sku: "HLG-PLG-006",
    category: "Electronics",
    purchasePrice: 14,
    sellingPrice: 29,
    stock: 2,
    image: img("4348404"),
  },
  {
    id: "p-007",
    name: "Northwind Wool Scarf",
    sku: "NWT-SCF-007",
    category: "Apparel",
    purchasePrice: 9,
    sellingPrice: 39,
    stock: 7,
    image: img("45055"),
  },
  {
    id: "p-008",
    name: "Pivot Adjustable Wrench",
    sku: "PVT-WRN-008",
    category: "Hardware",
    purchasePrice: 6,
    sellingPrice: 17,
    stock: 41,
    image: img("6194164"),
  },
  {
    id: "p-009",
    name: "Solace Ceramic Mug",
    sku: "SLC-MUG-009",
    category: "Home Goods",
    purchasePrice: 4,
    sellingPrice: 14,
    stock: 33,
    image: img("1566309"),
  },
  {
    id: "p-010",
    name: "Lumen LED Strip 2m",
    sku: "LMN-LD-010",
    category: "Electronics",
    purchasePrice: 9,
    sellingPrice: 22,
    stock: 1,
    image: img("3579155"),
  },
  {
    id: "p-011",
    name: "Drift Running Cap",
    sku: "DRF-CAP-011",
    category: "Apparel",
    purchasePrice: 5,
    sellingPrice: 19,
    stock: 27,
    image: img("2516968"),
  },
  {
    id: "p-012",
    name: "Forge Claw Hammer",
    sku: "FRG-HMR-012",
    category: "Hardware",
    purchasePrice: 7,
    sellingPrice: 21,
    stock: 15,
    image: img("2546735"),
  },
];

export const CUSTOMERS: Customer[] = [
  {
    id: "c-001",
    name: "Amara Okafor",
    email: "amara.okafor@northwind.co",
    phone: "+1 (415) 555-0182",
    totalPurchases: 1240,
  },
  {
    id: "c-002",
    name: "Jonas Vinter",
    email: "j.vinter@vinterstudio.dk",
    phone: "+45 32 14 77 90",
    totalPurchases: 865,
  },
  {
    id: "c-003",
    name: "Priya Raman",
    email: "priya@ramanexports.in",
    phone: "+91 98110 23456",
    totalPurchases: 2210,
  },
  {
    id: "c-004",
    name: "Marcus Delacroix",
    email: "m.delacroix@atelier.fr",
    phone: "+33 1 42 86 99 12",
    totalPurchases: 540,
  },
  {
    id: "c-005",
    name: "Sofia Brennan",
    email: "sofia.brennan@harbourline.ie",
    phone: "+353 1 902 4455",
    totalPurchases: 1675,
  },
  {
    id: "c-006",
    name: "Daniel Hsu",
    email: "daniel.hsu@meridian.tw",
    phone: "+886 2 2755 6611",
    totalPurchases: 980,
  },
];

export const SALES: Sale[] = [
  {
    id: "S-2041",
    date: "2026-07-01",
    customerName: "Amara Okafor",
    items: [
      {
        productId: "p-001",
        name: "Aurora Wireless Earbuds",
        price: 79,
        qty: 2,
      },
      { productId: "p-005", name: "Atlas Insulated Bottle", price: 24, qty: 1 },
    ],
    grandTotal: 182,
  },
  {
    id: "S-2040",
    date: "2026-06-29",
    customerName: "Priya Raman",
    items: [
      { productId: "p-003", name: "Field Canvas Tote", price: 34, qty: 4 },
      { productId: "p-007", name: "Northwind Wool Scarf", price: 39, qty: 2 },
    ],
    grandTotal: 214,
  },
  {
    id: "S-2039",
    date: "2026-06-28",
    customerName: "Sofia Brennan",
    items: [
      { productId: "p-002", name: "Meridian Desk Lamp", price: 49, qty: 1 },
    ],
    grandTotal: 49,
  },
  {
    id: "S-2038",
    date: "2026-06-27",
    customerName: "Jonas Vinter",
    items: [
      { productId: "p-009", name: "Solace Ceramic Mug", price: 14, qty: 6 },
      { productId: "p-011", name: "Drift Running Cap", price: 19, qty: 2 },
    ],
    grandTotal: 122,
  },
  {
    id: "S-2037",
    date: "2026-06-25",
    customerName: "Marcus Delacroix",
    items: [
      {
        productId: "p-008",
        name: "Pivot Adjustable Wrench",
        price: 17,
        qty: 3,
      },
      { productId: "p-012", name: "Forge Claw Hammer", price: 21, qty: 2 },
    ],
    grandTotal: 93,
  },
  {
    id: "S-2036",
    date: "2026-06-24",
    customerName: "Daniel Hsu",
    items: [
      { productId: "p-010", name: "Lumen LED Strip 2m", price: 22, qty: 5 },
    ],
    grandTotal: 110,
  },
  {
    id: "S-2035",
    date: "2026-06-22",
    customerName: "Amara Okafor",
    items: [
      { productId: "p-006", name: "Heliograph Smart Plug", price: 29, qty: 2 },
      {
        productId: "p-001",
        name: "Aurora Wireless Earbuds",
        price: 79,
        qty: 1,
      },
    ],
    grandTotal: 137,
  },
];

// 14-day sales trend for the dashboard chart
export const SALES_TREND = [
  { day: "Jun 22", total: 340 },
  { day: "Jun 23", total: 210 },
  { day: "Jun 24", total: 110 },
  { day: "Jun 25", total: 93 },
  { day: "Jun 26", total: 480 },
  { day: "Jun 27", total: 122 },
  { day: "Jun 28", total: 49 },
  { day: "Jun 29", total: 214 },
  { day: "Jun 30", total: 305 },
  { day: "Jul 01", total: 182 },
  { day: "Jul 02", total: 410 },
  { day: "Jul 03", total: 88 },
  { day: "Jul 04", total: 256 },
  { day: "Jul 05", total: 173 },
];
